// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynctjadvpolaxzdurrds.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InluY3RqYWR2cG9sYXh6ZHVycmRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyOTUyNjEsImV4cCI6MjA2Mzg3MTI2MX0.JPxBVxO5uBScTix9K5fbkOs-M4nJ0QyGPcEYP7wbSNM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);